# Physics Informed Neural Networks

This notebook implements PINNs from Raissi et al. 2017. Specifically, the notebook adapts the code implementation of Data-Driven Solutions of Nonlinear Partial Differential Equations from https://github.com/maziarraissi/PINNs, and the code by Michael Ito, to solve the force-field equation for solar modulation of cosmic rays. Michael Ito's code adaption use the TF2 API where the main mechanisms of the PINN arise in the train_step function efficiently computing higher order derivatives of custom loss functions through the use of the GradientTape data structure. 

In this application, our PINN is $h(r, p) = \frac{\partial f}{\partial r} + \frac{RV}{3k} \frac{\partial f}{\partial p}$ where $k=\beta(p)k_1(r)k_2(r)$ and $\beta = \frac{p}{\sqrt{p^2 + M^2}}$. We will approximate $f(r, p)$ using a neural network.

We have no initial data, but our boundary data will be given by $f(r_{HP}, p) = \frac{J(r_{HP}, T)}{p^2} = \frac{(T+M)^\gamma}{p^2}$, where $r_{HP} = 120$ AU (i.e. the radius of Heliopause), $M=0.938$ GeV, $\gamma$ is between $-2$ and $-3$, and $T = \sqrt{p^2 + M^2} - M$. Or, vice versa, $p = \sqrt{T^2 + 2TM}$.


In [7]:
# Imports
import numpy as np
import scipy.io
import tensorflow as tf

from pyDOE import lhs

import matplotlib
import matplotlib.pyplot as plt

tf.config.list_physical_devices(device_type=None)

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

## Load the Data

The data was gathered from https://github.com/maziarraissi/PINNs/tree/master/main/Data. 

In [8]:
# Constants
noise = 0.0   
M = 0.938 # GeV
gamma = -2.5 # Between -2 and -3

# Domain bounds
lb = np.array([0.0433, 1]) # (p, r) in (GeV, AU)
ub = np.array([1000.9376, 120]) # (p, r) in (GeV, AU)

# Assign number of data points
N_b = 50 # number of boundary data points
N_h = 20000 # number of collocation data points

# Create intial r, p, and T data
r = np.linspace(1, 120, 201) # r values
p = np.linspace(0.0433, 1000.9376, 256) # p values
T = np.linspace(0.001, 1000, 256) # T values
# print(r, p, T)
print(r.shape, p.shape, T.shape)

# Create boundary f data (f at r_HP)
f_exact = ((T + M)**gamma)/(p**2)
print(f_exact.shape)

P, R = np.meshgrid(p, r)
# print(len(P), len(R))
# print(P, R)

# Flatten and transpose data for ML
P_star = np.hstack((P.flatten()[:,None], R.flatten()[:,None]))

(201,) (256,) (256,)
(256,)


## PINN Class

The PINN class subclasses the Keras Model so that we can implement our custom fit and train_step functions.

Michael advises working through the TF2 API introduction to Gradients and Autodifferentiation in tensorflow https://www.tensorflow.org/guide/autodiff and Advanced Autodifferentiation in tensorflow https://www.tensorflow.org/guide/advanced_autodiff. These are the main data structures for the PINN used in the train_step function.

In [13]:
'''
Description: Defines the class for a PINN model implementing train_step, fit, and predict functions. Note, it is necessary 
to design each PINN seperately for each system of PDEs since the train_step is customized for a specific system. 
This PINN in particular solves the force-field equation for solar modulation of cosmic rays. Once trained, the PINN can predict the solution space given 
domain bounds and the input space. 
'''
class PINN(tf.keras.Model):
    def __init__(self, inputs, outputs, lower_bound, upper_bound, p, r, f_boundary, n_samples=20000, n_boundary=50):
        super(PINN, self).__init__(inputs=inputs, outputs=outputs)
        self.lower_bound = lower_bound
        self.upper_bound = upper_bound
        self.p = p
        self.r = r
        self.f_boundary = f_boundary
        self.n_samples = n_samples
        self.n_boundary = n_boundary
        
    '''
    Description: A system of PDEs are determined by 2 types of equations: the main partial differential equations 
    and the boundary value equations. These two equations will serve as loss functions which 
    we train the PINN to satisfy. If a PINN can satisfy BOTH equations, the system is solved. Since there are 2 types of 
    equations (PDE, Boundary Value), we will need 2 types of inputs. Each input is composed of a spatial 
    variable 'r' and a temporal variable 'p'. The different types of (p, r) pairs are described below.
    
    Inputs: 
        p, r: (batchsize, 1) shaped arrays : These inputs are used to derive the main partial differential equation loss.
        Train step first feeds (p, r) through the PINN for the forward propagation. This expression is PINN(p, r) = f. 
        Next, the partials f_p and f_r are obtained.We utilize TF2s GradientTape data structure to obtain all partials. 
        Once we obtain these partials, we can compute the main PDE loss and optimize weights wrt. to the loss. 
        
        p_boundary, r_boundary : (boundary_batchsize, 1) shaped arrays : These inputs are used to derive the boundary value
        equations. The boundary value loss relies on target data (**not an equation**), so we can just measure the MSE of 
        PINN(p_boundary, r_boundary) = f_pred_boundary and boundary_f.
        
        f_boundary: (boundary_batchsize, 1) shaped arrays : This is the target data for the boundary value inputs
        
    Outputs: total_loss, pinn_loss, boundary_loss
    '''
    def train_step(self, p, r, p_boundary, r_boundary, f_boundary):
        with tf.GradientTape(persistent=True) as t2: 
            with tf.GradientTape(persistent=True) as t1: 
                # Forward pass P (PINN data)
                P = tf.concat((p, r), axis=1)
                f = self.tf_call(P)

                # Forward pass P_boundary (boundary condition data)
                P_boundary = tf.concat((p_boundary, r_boundary), axis=1)
                f_pred_boundary = self.tf_call(P_boundary)

                # Calculate boundary loss
                boundary_loss = tf.math.reduce_mean(tf.math.square(f_pred_boundary - f_boundary))

            # Calculate first-order PINN gradients
            f_p = t1.gradient(f, p)
            f_r = t1.gradient(f, r)

        # Calculate resulting loss = PINN loss + boundary loss
        pinn_loss = self.pinn_loss(f, r, p, f_p, f_r)
        total_loss = pinn_loss + boundary_loss
        
        # Backpropagation
        gradients = t2.gradient(total_loss, self.trainable_variables)
        print(gradients)
        self.optimizer.apply_gradients(zip(gradients, self.trainable_variables))
        
        # Return losses
        return total_loss.numpy(), pinn_loss.numpy(), boundary_loss.numpy()
    
    '''
    Description: The fit function used to iterate through epoch * steps_per_epoch steps of train_step. 
    
    Inputs: 
        P_predict: (N, 2) array: Input data for entire spatial and temporal domain. Used for vizualization for
        predictions at the end of each epoch. Michael created a very pretty video file with it. 
        
        batchsize: batchsize for (p, r) in train step
        
        initial_batchsize: batchsize for (x_initial, t_initial) in train step
        
        boundary_batchsize: batchsize for (x_lower, t_boundary) and (x_upper, t_boundary) in train step
        
        epochs: epochs
    
    Outputs: Losses for each equation (PDE, Initial Value, Boundary Value), and predictions for each epoch.
    '''
    def fit(self, P_predict, batchsize=64, boundary_batchsize=16, epochs=20):
        # Initialize losses as zeros
        steps_per_epoch = np.ceil(self.n_samples / batchsize).astype(int)
        total_pinn_loss = np.zeros((epochs, ))
        total_boundary_loss = np.zeros((epochs, ))
        total_predictions = np.zeros((51456, 1, epochs)) # why 51456??
        
        # For each epoch, sample new values in the PINN and boundary areas and pass them to train_step
        for epoch in range(epochs):
            # Reset loss variables
            pinn_loss = np.zeros((steps_per_epoch,))
            boundary_loss = np.zeros((steps_per_epoch,))
            
            # For each step, get PINN and boundary variables and pass them to train_step
            for step in range(steps_per_epoch):
                # Get PINN p and r variables via uniform distribution sampling between lower and upper bounds
                p = tf.Variable(tf.random.uniform((batchsize, 1), minval=self.lower_bound[0], maxval=self.upper_bound[0]))
                r = tf.Variable(tf.random.uniform((batchsize, 1), minval=self.lower_bound[1], maxval=self.upper_bound[1]))
                
                # Get p_boundary and r_boundary variables by randomly sampling along r = r_HP = 120 AU
                p_idx = np.expand_dims(np.random.choice(self.f_boundary.shape[0], boundary_batchsize, replace=False), axis=1)
                p_boundary = self.p[p_idx]
                r_boundary = np.zeros((boundary_batchsize, 1)) + 120
                f_boundary = self.f_boundary[p_idx]
                
                # Pass variables through the model via train_step and get losses
                total_loss = self.train_step(p, r, p_boundary, r_boundary, f_boundary)
                pinn_loss[step] = total_loss[1]
                boundary_loss[step] = total_loss[2]
            
            # Calculate and print total losses for the epoch
            total_pinn_loss[epoch] = np.sum(pinn_loss)
            total_boundary_loss[epoch] = np.sum(boundary_loss)
            print(f'Training loss for epoch {epoch}: pinn: {total_pinn_loss[epoch]:.4f}, boundary: {total_boundary_loss[epoch]:.4f}')
            
            # Get prediction variable loss by the predict function (below)
            total_predictions[:, :, epoch] = np.expand_dims(self.predict(P_predict)[1], axis=1)
        
        # Return epoch losses
        return total_pinn_loss, total_boundary_loss, total_predictions
    
    # Predict for some P's the value of the neural network f(r, p)
    def predict(self, P, batchsize=2048):
        steps_per_epoch = np.ceil(P.shape[0] / batchsize).astype(int)
        preds = np.zeros((P.shape[0], 2))
        
        # For each step calculate start and end index values for prediction data
        for step in range(steps_per_epoch):
            start_idx = step * 64
            
            # If last step of the epoch, end_idx is shape-1. Else, end_idx is start_idx + 64 
            if step == steps_per_epoch - 1:
                end_idx = P.shape[0] - 1
            else:
                end_idx = start_idx + 64
                
            # Get prediction data and calculate h
            preds[start_idx: end_idx, :] = self(P[start_idx: end_idx, :]).numpy()
            f = np.sqrt(preds[:, 0]**2 + preds[:, 1]**2)
        
        # Return prediction data and h
        return preds, f
    
    def evaluate(self, ): 
        pass
    
    # pinn_loss calculates the PINN loss by calculating the MSE of the pinn function
    @tf.function
    def pinn_loss(self, f, r, p, f_p, f_r): 
        R = 1 # unknown
        V = 400 # km/s
        M = 0.938 # GeV
        k_0 = 1 # km^2/s
        k = (p/tf.math.sqrt(tf.math.square(p) + tf.math.square(M)))*k_0*r*p
        l_f = tf.math.reduce_mean(tf.math.square(f_r + ((R*V)/(3*k))*f_p))
        
        return l_f
    
    # tf_call passes inputs through the neural network
    @tf.function
    def tf_call(self, inputs): 
        return self.call(inputs, training=True)

In [14]:
# Define neural network as 6 layers (4 hidden), with activation functions of tanh for hidden layers and linear for the output layer
inputs = tf.keras.Input((2))
x_ = tf.keras.layers.Dense(100, activation='tanh')(inputs)
x_ = tf.keras.layers.Dense(100, activation='tanh')(x_)
x_ = tf.keras.layers.Dense(100, activation='tanh')(x_)
x_ = tf.keras.layers.Dense(100, activation='tanh')(x_)
outputs = tf.keras.layers.Dense(2, activation='linear')(x_)

# Get keras Adam optimizer
optimizer = tf.keras.optimizers.Adam(learning_rate=5e-4)

# Define the PINN using the model defined above
pinn = PINN(inputs=inputs, outputs=outputs, lower_bound=lb, upper_bound=ub, 
            p=p, r=r, f_boundary=f_exact)

# Compile the PINN and get loss and prediction outputs
pinn.compile(optimizer="adam")
pinn_loss, boundary_loss, predictions = pinn.fit(P_predict=P_star, batchsize=2048, 
                                               boundary_batchsize=64, epochs=1200)

[None, None, None, None, None, None, None, None, None, None]


ValueError: No gradients provided for any variable: (['dense_15/kernel:0', 'dense_15/bias:0', 'dense_16/kernel:0', 'dense_16/bias:0', 'dense_17/kernel:0', 'dense_17/bias:0', 'dense_18/kernel:0', 'dense_18/bias:0', 'dense_19/kernel:0', 'dense_19/bias:0'],). Provided `grads_and_vars` is ((None, <tf.Variable 'dense_15/kernel:0' shape=(2, 100) dtype=float32, numpy=
array([[-0.18240786, -0.12136189,  0.10202342, -0.11690237,  0.14446056,
         0.12863079,  0.22357962, -0.21971944, -0.21990113, -0.12652513,
         0.20022923,  0.12606889,  0.2325086 ,  0.22600067, -0.11639403,
         0.20897132, -0.17634717,  0.13730332, -0.06520849,  0.13826415,
        -0.1309739 ,  0.06028718, -0.19411199, -0.12039003, -0.00083759,
        -0.08642328,  0.20541418, -0.14166847,  0.01872501,  0.20606712,
        -0.06493215,  0.09048954, -0.22403544,  0.03089866,  0.01542372,
        -0.22834022,  0.10889909, -0.07259865, -0.06819643, -0.09579815,
        -0.14678124,  0.23208746, -0.14895663, -0.08917245, -0.03694282,
        -0.22013792, -0.03379941, -0.18506445, -0.07803114, -0.05392244,
        -0.1986092 , -0.00962116,  0.12743357, -0.16170211,  0.02628365,
         0.0855726 ,  0.19176468, -0.11215714,  0.18123165,  0.03882179,
        -0.14437711,  0.23464036,  0.07651207, -0.01902188, -0.13711515,
         0.11865118, -0.22223096,  0.05041993, -0.13690352, -0.10643448,
        -0.13913001, -0.08345483,  0.11185458,  0.03727421, -0.09086262,
         0.14238718,  0.07577983, -0.08751021,  0.01522961,  0.21507117,
        -0.23221207,  0.03510118, -0.12265503, -0.21210337,  0.2136909 ,
        -0.04031588, -0.12203711, -0.16274707,  0.14924112,  0.23469034,
        -0.15027966, -0.17337975, -0.16581944,  0.02028438, -0.05393384,
         0.05356005,  0.14159319,  0.19022411,  0.00327446, -0.19063057],
       [-0.19818014, -0.03633104,  0.1355218 , -0.0988604 , -0.05843106,
        -0.05829847,  0.2379745 , -0.18181792,  0.07804427,  0.05974802,
        -0.13634071,  0.00142729, -0.1554177 , -0.15096304, -0.0383005 ,
         0.03296256, -0.01549768, -0.05857852, -0.05895236, -0.05501661,
        -0.0762329 , -0.22709745, -0.08174247,  0.1067442 ,  0.02198979,
         0.12122756,  0.09236231,  0.12500176,  0.24173793, -0.07130244,
        -0.03861865,  0.03193125,  0.17548424, -0.0363625 ,  0.01076615,
        -0.08281176, -0.16280872, -0.1361492 ,  0.10658363, -0.08253425,
        -0.11574292, -0.17396593,  0.12138432,  0.19463381,  0.18570185,
         0.05762035,  0.15495306, -0.18784647,  0.12981799,  0.02870461,
         0.21040615,  0.2328408 ,  0.149988  , -0.16402847,  0.17263728,
        -0.18062973,  0.02093861, -0.08596519, -0.11156483, -0.201929  ,
        -0.0006943 , -0.1035274 ,  0.2229566 , -0.14806582, -0.21653791,
         0.1342524 , -0.02518782,  0.17467302, -0.16677499, -0.18262736,
         0.00466144,  0.0668003 ,  0.2161052 ,  0.18739724, -0.14360845,
         0.22889581, -0.2400817 , -0.21007395,  0.04951334, -0.07827279,
        -0.03486454, -0.09049387, -0.16858763,  0.23205107, -0.1601442 ,
        -0.0532278 ,  0.03511423,  0.0582462 ,  0.13616231, -0.04446609,
         0.13540196, -0.22981533,  0.11763051, -0.019373  ,  0.04482558,
        -0.06831653,  0.03943798,  0.01466852, -0.00456402,  0.02080491]],
      dtype=float32)>), (None, <tf.Variable 'dense_15/bias:0' shape=(100,) dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32)>), (None, <tf.Variable 'dense_16/kernel:0' shape=(100, 100) dtype=float32, numpy=
array([[ 0.01458852,  0.03009862,  0.08213121, ...,  0.11993459,
        -0.14862153, -0.05568251],
       [-0.05748112,  0.14426392,  0.02149165, ...,  0.02441345,
        -0.00187823, -0.01149641],
       [-0.16827545, -0.04047048, -0.05867006, ...,  0.10928407,
         0.10429937, -0.07603721],
       ...,
       [-0.13487919,  0.02480936,  0.16686463, ...,  0.08285517,
        -0.04325308,  0.00786197],
       [ 0.08684281,  0.04430738, -0.12566963, ...,  0.06895417,
        -0.08524632,  0.11915737],
       [-0.14443654, -0.13706549,  0.04043852, ..., -0.13823117,
        -0.0419887 ,  0.09253296]], dtype=float32)>), (None, <tf.Variable 'dense_16/bias:0' shape=(100,) dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32)>), (None, <tf.Variable 'dense_17/kernel:0' shape=(100, 100) dtype=float32, numpy=
array([[ 0.04767407, -0.13440417,  0.14239284, ..., -0.05958711,
         0.05638677,  0.06275433],
       [ 0.08496922, -0.00571556, -0.07990374, ...,  0.01876575,
         0.00837618, -0.1407812 ],
       [ 0.05461115,  0.13466486,  0.0556266 , ..., -0.11159541,
         0.03832585,  0.15228128],
       ...,
       [-0.15925936, -0.06102579,  0.14862186, ...,  0.05930172,
         0.06116438,  0.06691389],
       [ 0.02610207,  0.08327788, -0.12502179, ...,  0.15546718,
         0.11468154,  0.13161245],
       [-0.1173559 ,  0.13865834,  0.12973508, ...,  0.12454173,
         0.12299007, -0.15545982]], dtype=float32)>), (None, <tf.Variable 'dense_17/bias:0' shape=(100,) dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32)>), (None, <tf.Variable 'dense_18/kernel:0' shape=(100, 100) dtype=float32, numpy=
array([[-0.0974521 , -0.11151624, -0.06493737, ..., -0.16232471,
        -0.08517669,  0.01054113],
       [-0.06863289, -0.13549425, -0.05443866, ..., -0.14521842,
        -0.11521205,  0.02580296],
       [ 0.04989204, -0.11395779,  0.04757406, ...,  0.04287833,
         0.15914014, -0.10883548],
       ...,
       [-0.17153898,  0.01464592,  0.16804117, ...,  0.07534878,
         0.15140468,  0.15067893],
       [ 0.14783737, -0.03440022,  0.06975558, ...,  0.14722532,
        -0.08526973, -0.03517725],
       [ 0.00612913,  0.01220606,  0.0181298 , ...,  0.04200236,
        -0.10417832, -0.17194264]], dtype=float32)>), (None, <tf.Variable 'dense_18/bias:0' shape=(100,) dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32)>), (None, <tf.Variable 'dense_19/kernel:0' shape=(100, 2) dtype=float32, numpy=
array([[-0.01284733,  0.06872854],
       [-0.02350725, -0.06014633],
       [-0.10827859, -0.008564  ],
       [-0.2115527 , -0.2312235 ],
       [-0.23525482,  0.23713574],
       [ 0.15200746, -0.05958791],
       [-0.02140415,  0.24143088],
       [ 0.09832361, -0.063449  ],
       [-0.07986112,  0.19104564],
       [ 0.2389296 , -0.12580425],
       [-0.2389185 ,  0.23192513],
       [-0.06927712, -0.08337474],
       [ 0.11592939,  0.00731845],
       [-0.13990712, -0.14971712],
       [-0.08225942,  0.11926198],
       [ 0.2099841 ,  0.22732222],
       [ 0.05803168, -0.04866858],
       [ 0.02926847, -0.20371492],
       [-0.00106572,  0.16663799],
       [-0.17968239, -0.00087345],
       [-0.047803  , -0.10260352],
       [ 0.06157246,  0.22380748],
       [-0.21343699, -0.03971918],
       [-0.23312506, -0.02472001],
       [ 0.22444871,  0.18935144],
       [ 0.10565802,  0.00053205],
       [-0.20716962,  0.09781528],
       [-0.14497109, -0.16938266],
       [ 0.23132485, -0.00796157],
       [ 0.20563748,  0.23128062],
       [ 0.13364995,  0.15346992],
       [ 0.0806624 , -0.05589543],
       [ 0.10150483, -0.17740062],
       [-0.05539368, -0.10250533],
       [ 0.20588377, -0.12650329],
       [ 0.11214024, -0.05853896],
       [ 0.05327955,  0.24078861],
       [-0.05784222,  0.2002334 ],
       [ 0.18708271,  0.2376689 ],
       [-0.06636477, -0.0735283 ],
       [-0.04323581, -0.20108643],
       [ 0.13376772, -0.09543057],
       [ 0.10866082,  0.0823673 ],
       [-0.12830782,  0.0703381 ],
       [ 0.01490295,  0.12604463],
       [ 0.03873071,  0.14190406],
       [-0.0569649 ,  0.00545967],
       [-0.1999012 ,  0.2364111 ],
       [ 0.06373084,  0.21572402],
       [ 0.04182985, -0.01754931],
       [-0.01257473, -0.20702581],
       [-0.12694848, -0.19737916],
       [-0.11627924, -0.13125366],
       [-0.16005936, -0.07873984],
       [ 0.08641535, -0.20089653],
       [ 0.0109641 ,  0.04573271],
       [ 0.16538483, -0.23235518],
       [-0.08671911, -0.12152768],
       [ 0.12433532,  0.07000238],
       [ 0.12315613,  0.16278142],
       [ 0.01010123,  0.00612962],
       [-0.06647903, -0.19441111],
       [-0.16921538, -0.01031332],
       [-0.06291667,  0.11513194],
       [ 0.16262916, -0.03924079],
       [ 0.1433805 , -0.08618568],
       [-0.06499866, -0.20042439],
       [ 0.06609535, -0.05583304],
       [ 0.03776631,  0.04200605],
       [-0.0552792 ,  0.142609  ],
       [ 0.06582087, -0.1986975 ],
       [ 0.17633045, -0.21100342],
       [-0.0367095 , -0.21450739],
       [-0.01687084, -0.00473449],
       [ 0.14940718,  0.23252687],
       [-0.1462403 ,  0.04078656],
       [ 0.10433012, -0.14835674],
       [-0.23703998,  0.08951008],
       [ 0.216656  , -0.13681382],
       [ 0.14031515, -0.15691039],
       [ 0.02246848,  0.17735752],
       [ 0.04455051, -0.08906038],
       [ 0.08704531,  0.05980632],
       [ 0.13024941,  0.09846255],
       [-0.19147003,  0.1072017 ],
       [-0.03931376, -0.01768468],
       [ 0.07736695, -0.09180962],
       [-0.07602125,  0.153029  ],
       [ 0.10845205,  0.07303563],
       [-0.08308579, -0.10829628],
       [-0.02454075, -0.01023242],
       [-0.13190223, -0.20956439],
       [-0.04929309, -0.18650661],
       [ 0.11686784, -0.11632361],
       [-0.03330934,  0.23671177],
       [ 0.18725592, -0.16825086],
       [ 0.16164508, -0.07411951],
       [ 0.05920741,  0.07127729],
       [-0.14765069, -0.11798248],
       [-0.17135194, -0.07588403]], dtype=float32)>), (None, <tf.Variable 'dense_19/bias:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>)).

In [ ]:
import pickle as pkl

# Save loss data, prediction data, and h-function approximation
with open('./figures/pinn_loss.pkl', 'wb') as file:
    pkl.dump(pinn_loss, file)
    
with open('./figures/boundary_loss.pkl', 'wb') as file:
    pkl.dump(boundary_loss, file)
    
with open('./figures/predictions.pkl', 'wb') as file:
    pkl.dump(predictions, file)
    
with open('./figures/true.pkl', 'wb') as file:
    pkl.dump(h_star, file)